export default [
    { "firstName": "corgi",
        "lastName": "corgi",
        "username" : "corgi",
        "handle": "@corgi",
        "password": "12345",
        "email": "corgi@gmail.com",
        "type": "WRITER",
        "_id": "101" },
    { "firstName": "cookie",
        "lastName": "dog",
        "username" : "cookiethedog",
        "handle": "@cookiethedog",
        "password": "123456",
        "email": "cookiedog@gmail.com",
        "type": "WRITER",
        "_id": "123" },
    { "firstName": "max",
        "lastName": "manatee",
        "username" : "maxthemanatee",
        "handle": "maxthemanatee",
        "email": "maxmanataee@gmail.com",
        "password": "98765",
        "type": "SUBSCRIBER",
        "_id": "567" },
    {   "firstName": "casper",
        "lastName": "cat",
        "username": "casperthecat",
        "handle" : "casperthecat",
        "email": "caspercat@gmail.com",
        "password": "567890",
        "type": "WRITER",
        "_id": "789" }
]
